### ISSUE TITLE
Health Check does not work

### ISSUE THREAD

**Issue by JesseMarkowitz** [Start9Labs/cryptpad-wrapper#6]
Environment - EOS 3.1.1, CryptPad 5.0.0, Chrome Version 104.0.5112.81 (Official Build) (64-bit) on Windows 10

CryptPad Services page shows:

>HEALTH CHECKS
>Web Interface
>Web interface is unreachable

NOTE: Health check should implement the CryptPad built in Checkup (https://reallylonglocaladdressgoeshere.local/checkup/).  There are currently 43 tests.  All of them should pass for the health check.  Getting some of those tests to pass might require adjusting the default / initial configuration in the s9pk...

**Comment by chrisguida** [comment]
Yep, getting that checkup to pass all those tests is most likely gonna be a project. But necessary for the beta I think.

**Comment by chrisguida** [comment]
Implementing this in docker for now that just checks the UI for liveness. Saving the "checkup" work for a different issue, to be completed once the Embassy Pro launches and people may use their embassies to host publicly listed cryptpad instances.
